# Imports

In [4]:
# Imports
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsbombpy import sb
from mplsoccer import Pitch, VerticalPitch, Radar, FontManager, grid, PyPizza

import warnings
warnings.filterwarnings('ignore')

# Show Specific Number Of Rows And Columns
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 160)

# Imports Libary And Modules That Use HTML Code To Effect The Cells In The Screen
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Data

In [5]:
# Open Data File, Then Name File Using 'as'
with open('Celtic Technical StatsBomb Data.csv', 'r') as file:
    
# Create Variable For The Reader Object, Use *csv.reader* Calling The File Name
    csv_reader = csv.reader(file)
    
# Use For Loop To Get Each Row Of The File
    for row in csv_reader:
        
# Use Print Function, Printing Each *row* To Show Data
        print(row)

['Account', 'Default Radar Template', 'Name', 'Team', 'Competition', 'Competition Type', 'Competition Rank', 'Season', 'Nationality', 'Country Code', 'Date of Birth', 'Age', 'Woman Player?', 'Team Color 1', 'Team Color 2', 'Player Id', 'Player Name', 'First Name', 'Last Name', 'Nickname', 'Weight', 'Height', 'Birth Date', 'Country Id', 'Country', 'Team Id', 'Team Color 1st', 'Team Color 2nd', 'Competition Id', 'Competition Name', 'Season Id', 'Seasons', 'Primary Position', 'Secondary Position', 'Most Recent Match', 'Player SBData Id', '90s Played', 'Appearances', 'Minutes Played', 'Starting Appearances', 'Assists', 'Key Passes', 'Open Play Assists', 'Open Play Key Passes', 'Open Play xG Assisted', 'Set Piece Assists', 'Set Piece Key Passes', 'Set-Piece xG Assisted', 'xG Assisted', 'Dispossessed', 'Dribble%', 'Dribbles', 'Failed Dribbles', 'Fouls Won', 'Penalty wins', 'Successful Dribbles', 'Turnovers', 'Over/Underperformance', 'Scoring Contribution', 'Shots & Key Passes', 'xG & xG Assisted', 'Goal Conversion%', 'Goals & Penalty Goals', 'Non-Penalty Goals', 'Penalty Conversion%', 'Shooting%', 'Shots', 'Shot Touch%', 'xG', 'xG/Shot', 'Red Cards', 'Second Yellow Cards', 'Yellow Cards', 'Aggressive Actions', 'Average Defensive Action Distance', 'Blocks/Shot', 'Clearances', 'Defensive Action Regains', 'Interceptions', 'PAdj Clearances', 'PAdj Interceptions', 'Aerial Win%', 'Aerial Wins', 'Dribbled Past', 'Dribbles Successfully Defended%', 'Errors', 'Fouls', 'PAdj Tackles', 'PAdj Tackles & Interceptions', 'Tack/Dribbled Past%', 'Tackles', 'Tackles & Interceptions', 'Average Pressure Distance', 'Counterpressure Regains', 'Counterpressures', 'Counterpressures in Opposing Half', 'Counterpressures in Opposing Half%', 'PAdj Pressures', 'Pressure Regains', 'Pressures', 'Pressures in Opposing Half', 'Pressures in Opposing Half%', 'Claims - CCAA%', 'Goalkeeper Aggressive Distance', 'Pass into Danger%', 'Pass into Pressure%', 'Positive Outcome', 'Positive Outcome%', 'All Shots Faced', 'Expected Save%', 'Goals Conceded', 'Goals Saved Above Average', 'Positioning Error', 'PSxG Faced', 'Save%', 'Shots Faced', 'Shots Faced On Target%', 'Shot Stopping%', 'xG Faced', 'Crossing%', 'Open Play Final Third Passes', 'OP Passes Into Box', 'Passes Inside Box', 'Passes Into Box', 'Passes + Touches In Box', 'Set Piece Passes Into Box', 'Successful Box Cross%', 'Successful Crosses', 'Throughballs', 'Touches In Box', 'Carries', 'Carry%', 'Carry Length', 'Deep Progressions', 'xGBuildup', 'xGChain', 'Final Third Pass Backward%', 'Final Third Pass Forward%', 'Final Third Pass Sideways%', 'Pass Backward%', 'Pass Forward%', 'Pass Sideways%', 'Average Pass Distance', 'Being Pressured Change in Pass%', 'Left to Right Footedness%', 'Long Ball%', 'Long Balls', 'Open Play Passes', 'Passes Being Pressured%', 'Passing%', 'Pressured Long Balls', 'Pressured Pass%', 'Unpressured Long Balls', 'Being Pressured Change in Pass Length', 'Pass Length', 'Pass Length Ratio', 'Pressured Pass Length', 'Pressured Pass Length Ratio', 'Successful Pass Length', 'Successful Pressured Pass Length']
['107', 'Striker', 'Aaron Connolly', 'Brighton Hove Albion', 'Premier League', '1', '1', '2020/2021', 'Republic of Ireland', 'ie', '28/01/2000', '21', 'FALSE', '#005daa', '#959595', '3920732', 'Aaron Connolly', 'Aaron', 'Connolly', 'Aaron Connolly', '', '', '28/01/2000', '1166', 'Premier League', '199', '#005daa', '#959595', '1002', 'Premier League', '1090', '2020/2021', 'Centre Forward', 'Left Centre Forward', '00:00.0', '24835', '9.571667', '17', '861.45', '9', '0', '0.52237505', '0', '0.52237505', '0.019415723', '0', '0', '0', '0.019415723', '1.5671252', '0.8', '1.0447501', '0.20895003', '1.6716002', '0.104475014', '0.8358001', '3.2387254', '-0.17599595', '0.20895003', '2.9253004', '0.38494593', '0.086956522', '0.20895003', '0.20895003', '', '0.347826087', '2.4029253', '0.045548654', '0.36553022', '0.152118859', '0', '0', '0', '14.417552', '62.083176', '0.012048193', '0.104475014', '2.9253004', '0', '0.12969056', '0', '0.268292683', '1.1492251', '0.41790006', '0.4', '0', '0.7313251', '1.0160846', '1.0160846', '0.636363636', '0.7313251', '0.7313251', '63.62611', '0.20895003', '2.1939752', '2.0895002', '0.95238096', '14.929437', '2.4029253', '12.954902', '9.925126', '0.766129', '0', '0', '0.15841584', '0.10891089', '2.2566602', '0.147541', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '3.8655756', '0.104475014', '0', '0.104475014', '11.074351', '0', '0', '0', '0', '10.969876', '12.954902', '0.7177419', '6.45185', '1.0447501', '0.3683567', '0.5342792', '0.243243243', '0.054054054', '0.702702703', '0.306930693', '0.108910891', '0.584158416', '62.93147', '0.081458144', '0.130434783', '0.5', '0.104475014', '9.507226', '0.217821782', '0.782178218', '0.20895003', '0.863636364', '0.104475014', '-0.9575332', '13.86780873', '1.0438414', '12.91027546', '0.86628264', '14.47579299', '11.18394756']
['107', 'Striker', 'Aaron Collins', 'Forest Green Rovers', 'League Two', '1', '4', '2020/2021', 'Wales', 'gb-wls', '27/05/1997', '24', 'FALSE', '#9bee7c', '#fd57ad', '636438', 'Aaron Collins', 'Aaron', 'Collins', '', '74', '178', '27/05/1997', '979', 'League Two', '480857', '#9bee7c', '#fd57ad', '1005', 'League Two', '1090', '2020/2021', 'Left Centre Forward', 'Right Centre Forward', '30:00.0', '9806', '41.697598', '46', '3752.784', '38', '0.16787538', '1.1991098', '0.14389318', '0.9113234', '0.11474792', '0.023982197', '0.28778636', '0.021713316', '0.13646124', '2.1104333', '0.5046729', '2.566095', '1.2710564', '1.2710564', '0.023982197', '1.2950386', '3.8611333', '-0.12317057', '0.33575076', '4.2928133', '0.45892125', '0.054263566', '0.26380417', '0.16787538', '1', '0.279069767', '3.093703', '0.040569395', '0.3224601', '0.104231095', '0', '0', '0.14389318', '14.461264', '57.80135', '0.016216216', '0.5755727', '1.9905223', '0.4556617', '0.55360675', '0.46755195', '0.211538462', '0.79141253', '0.7434481', '0.25641027', '0', '0.83937687', '0.8164559', '1.284008', '0.53030303', '0.83937687', '1.2950386', '59.98882', '0.16787538', '2.7339702', '2.2783086', '0.8333333', '13.067722', '1.7027359', '12.854457', '8.969341', '0.6977612', '0', '0', '0.19056262', '0.07803993', '5.3240476', '0.3397093', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0.293333333', '10.120487', '0.8873413', '0.4556617', '1.1511455', '7.6263385', '0.26380417', '0.229166667', '0.52760834', '0.16787538', '6.738997', '26.596256', '0.79170424', '6.9734', '4.0529914', '0.45803833', '0.6518157', '0.151658768', '0.206161137', '0.642180095', '0.18784029', '0.204174229', '0.607985481', '66.79167', '-0.054410875', '0.206278027', '0.444444444', '1.8226469', '22.087603', '0.185117967', '0.652450091', '1.0072522', '0.598039216', '3.669276', '-3.607311', '20.80484347', '0.90546465', '17.19753265', '0.94791394', '18.8380509', '16.3017807']
['107', 'Striker', 'Aaron Drinan', 'Ipswich Town', 'League One', '1', '3', '2020/2021', 'Republic of Ireland', 'ie', '06/05/1998', '23', 'FALSE', '#0060aa', '#e2192b', '5273390', 'Aaron Drinan', 'Aaron', 'Drinan', '', '', '', '06/05/1998', '1166', 'League One', '111', '#0060aa', '#e2192b', '1004', 'League One', '1090', '2020/2021', 'Centre Forward', 'Left Centre Forward', '00:00.0', '47357', '9.127778', '22', '821.50006', '6', '0', '1.0955569', '0', '1.0955569', '0.12451568', '0', '0', '0', '0.12451568', '1.752891', '0.46153846', '1.4242238', '0.76688975', '0.5477784', '0', '0.6573341', '3.8344488', '-0.17910424', '0.109555684', '2.410225', '0.2886599', '0.083333333', '0.109555684', '0.109555684', '', '0.416666667', '1.3146682', '0.013412817', '0.1641442', '0.124855995', '0', '0', '0.21911137', '25.197805', '63.5198', '0.009708738', '0.6573341', '3.1771147', '0.8764455', '0.60998505', '0.58165497', '0.316239316', '4.0535603', '0.43822274', '0', '0', '1.6433353', '0.8410386', '1.4226936', '0.636363636', '0.76688975', '1.6433353', '65.14356', '0.32866704', '4.491783', '4.3822274', '0.9756098', '21.695127', '2.410225', '22.78758', '18.076687', '0.7932692', '0', '0', '0.30769232', '0.11282051', '3.242848', '0.2893451', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0.4', '8.435787', '0.32866704', '0.76688975', '0.32866704', '11.39379', '0', '0.333333333', '0.43822274', '0.109555684', '11.0651245', '17.638466', '0.7515528', '5.4764657', '1.0955569', '0.39730188', '0.45014474', '0.233766234', '0.090909091', '0.675324675', '0.18974359', '0.164102564', '0.646153846', '67.54308', '-0.20391135', '0.198113208', '0.333333333', '0.21911137', '21.144247', '0.302564103', '0.661538462', '0.6573341', '0.457627119', '0.6573341', '-1.079741', '13.1229705', '0.9533459', '12.0432291', '0.99227697', '12.51072989', '11.95021915']
['107', 'Striker', 'Aaron Jarvis', 'Scunthorpe United', 'League Two', '1', '4', '2020/2021', 'England', 'gb-eng', '21/08/1998', '22', 'FALSE', '#00acdd', '#a83249', '6794672', 'Aaron Jarvis', '', '', '', '80', '188', '21/08/1998', '618', 'League Two', '158', '#00acdd', '#a83249', '1005', 'League Two', '1090', '2020/2021', 'Centre Forward', 'Right Centre Forward', '00:00.0', '15276', '7.28037', '13', '655.23334', '6', '0', '0.41206694', '0', '0.41206694', '0.024661962', '0', '0', '0', '0.024661962', '0.41206694', '0.25', '0.5494226', '0.41206694', '1.7856234', '0', '0.13735566', '5.494226', '-0.12409132', '0.2747113', '2.1976905', '0.3988026', '0.153846154', '0.2747113', '0.2747113', '', '0.307692308', '1.7856234', '0.018480493', '0.37414062', '0.209529418', '0', '0', '0.2747113', '11.125808', '58.29921', '0', '0.8241339', '1.7856234', '0.13735566', '0.59576666', '0.2116968', '0.342857143', '4.944803', '0.2747113', '0.5', '0', '1.9229791', '0.5038779', '0.7155746', '0.714285714', '0.68677825', '0.8241339', '61.81606', '0.13735566', '1.3735565', '0.8241339', '0.6', '7.691807', '1.3735565', '8.51605', '6.1810045', '0.7258065', '0', '0', '0.2777778', '0.0952381', '1.8130945', '0.18282549', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '', '5.9062924', '0.13735566', '0.2747113', '0.13735566', '8.653406', '0', '0', '0', '0', '8.51605', '15.246477', '0.6756757', '4.0879197', '1.0988452', '0.34709397', '0.4769821', '0.23255814', '0.046511628', '0.720930233', '0.19047619', '0.126984127', '0.682539683', '63.982933', '-0.014096186', '0.163636364', '0.333333333', '0.13735566', '17.0321', '0.531746032', '0.611111111', '1.0988452', '0.597014925', '0.13735566', '-0.1407263', '15.32245164', '0.91807693', '15.1817255', '0.8277466', '14.0671894', '12.56662178']
['107', 'Striker', 'Aaron Leya Iseka', 'Metz', 'Ligue1', '1', '1', '2020/2021', 'Belgium', 'be', '15/11/1997', '23', 'FALSE', '#b0053a', '#959595', '14201', 'Aaron Leya Iseka', 'Aaron', 'Leya Iseka', '', '78', '180', '15/11/1997', '483', 'Ligue1', '506', '#b0053a', '#959595', '1007', 'Ligue 1', '1090', '2020/2021', 'Centre Forward', 'Left Centre Forward', '00:00.0', '9936', '11.81074', '21', '1062.9667', '12', '0', '1.0160244', '0', '1.0160244', '0.060223084', '0', '0', '0', '0.060223084', '1.6933739', '0.6086956', '1.94738', '0.76201826', '1.100693', '0', '1.1853617', '3.4714165', '-0.09221556', '0.16933739', '2.5400608', '0.26155296', '0.111111111', '0.33867478', '0.16933739', '0.6666667', '0.333333333', '1.5240365', '0.017356475', '0.20132986', '0.132103046', '0', '0', '0.33867478', '13.377654', '60.321053', '0.02173913', '0.33867478', '1.6933739', '0.16933739', '0.25672787', '0.122356', '0.364864865', '2.2860548', '0.5926809', '0.3', '0', '2.3707235', '0.5382549', '0.6606109', '0.5625', '0.76201826', '0.93135566', '64.370125', '0.16933739', '2.5400608', '2.201386', '0.8666667', '7.8477297', '0.93135566', '10.244912', '8.212863', '0.8016529', '0', '0', '0.18686868', '0.11111111', '2.573928', '0.16675808', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '5.0801215', '0.16933739', '0.084668696', '0.16933739', '10.583587', '0', '0', '0', '0.2540061', '10.414249', '17.357082', '0.7609756', '5.144907', '2.0320487', '0.23155569', '0.38703823', '0.216666667', '0.116666667', '0.666666667', '0.196969697', '0.111111111', '0.691919192', '57.74835', '-0.10808081', '0.097744361', '0.555555556', '0.42334348', '16.087051', '0.277777778', '0.762626263', '0.42334348', '0.654545455', '0.67734957', '-0.52073544', '15.33092275', '0.9749993', '14.81018734', '0.9934688', '14.94763911', '14.71345901']
['107', 'Striker', 'Aaron Martin', 'Harrogate Town', 'League Two', '1', '4', '2020/2021', 'England', 'gb-eng', '05/07/1991', '29', 'FALSE', '#E3D151', '#3F93BE', '14105281', 'Aaron Martin', '', '', '', '', '', '05/07/1991', '618', 'League Two', '924791', '#E3D151', '#3F93BE', '1005', 'League Two', '1090', '2020/2021', 'Left Centre Forward', 'Right Centre Forward', '00:00.0', '48387', '27.64944', '36', '2488.4497', '27', '0.18083547', '1.0850129', '0.18083547', '1.0850129', '0.068298', '0', '0', '0', '0.068298', '1.8083549', '0.5555556', '1.3020155', '0.57867354', '0.9041774', '0', '0.7233419', '5.0633936', '-0.045024373', '0.36167094', '3.833712', '0.4066953', '0.065789474', '0.18083547', '0.18083547', '', '0.289473684', '2.7486992', '0.018374847', '0.33839738', '0.123111825', '0', '0', '0.108501285', '23.074608', '59.21122', '0.033088235', '1.4466838', '2.604031', '0.57867354', '1.341389', '0.5718952', '0.441558442', '13.526494', '0.6871748', '0.24', '0', '3.1103704', '1.4687471', '2.0406425', '0.693548387', '1.5551852', '2.1338587', '63.179344', '0.108501285', '3.5082083', '2.9657018', '0.8453608', '17.747606', '1.880689', '18.409052', '13.273324', '0.7210216', '0', '0', '0.30567083', '0.10650069', '3.461191', '0.23205625', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0.25', '6.546244', '0.6148406', '0.5063393', '0.6148406', '15.44335', '0', '0.176470588', '0.14466839', '0.07233419', '14.828509', '16.311361', '0.6585366', '4.7911844', '1.1935142', '0.5085013', '0.65354776', '0.149171271', '0.193370166', '0.657458564', '0.098201936', '0.302904564', '0.598893499', '62.679382', '-0.08618157', '0.106280193', '0.297297297', '0.39783806', '25.931808', '0.536652835', '0.48824343', '1.9891902', '0.402061856', '0.7956761', '-0.40169004', '15.85770823', '0.95939374', '15.45601845', '1.009668', '15.21378558', '15.60544682']
['107', 'Striker', 'Aarn Rey', 'Sabadell', 'La Liga2', '1', '2', '2020/2021', 'Spain', 'es', '19/05/1998', '23', 'FALSE', '#3399ff', '#ed2a14', '14106016', 'Aarn Rey', '', '', 'Aarn Rey', '', '', '19/05/1998', '26', 'La Liga2', '742', '#3399ff', '#ed2a14', '1042', 'La Liga 2', '1090', '2020/2021', 'Right Centre Forward', 'Left Centre Midfielder', '00:00.0', '49327', '10.039815', '25', '903.5833', '7', '0.09960344', '1.1952412', '0.09960344', '0.99603426', '0.097756155', '0', '0.19920687', '0.022023031', '0.1197792', '1.2948446', '0.74285716', '3.48612', '0.8964309', '1.394448', '0', '2.5896893', '3.0877063', '-0.14375345', '0.09960344', '2.3904824', '0.24335688', '0', '0', '0', '', '0.166666667', '1.1952412', '0.01572327', '0.12357771', '0.103391439', '0', '0', '0.09960344', '16.135756', '46.306328', '0', '0.09960344', '2.5896893', '0.2988103', '0.05117971', '0.34778833', '0.368421053', '0.697224', '0.7968275', '0.27272728', '0', '0.8964309', '0.6425194', '0.9903078', '0.529411765', '0.8964309', '1.1952412', '47.022976', '0.19920687', '1.9920685', '1.0956378', '0.55', '13.503251', '2.4900858', '14.342895', '6.1754127', '0.43055555', '0', '0', '0.15412186', '0.10035843', '3.77497', '0.30539888', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0.363636364', '7.1714473', '0.5976206', '0.39841375', '0.8964309', '3.7849305', '0.2988103', '0', '0.39841375', '0.19920687', '3.18731', '27.29134', '0.8430657', '6.0471206', '3.685327', '0.36809367', '0.4314909', '0.125', '0.180555556', '0.694444444', '0.161290323', '0.154121864', '0.684587814', '57.19294', '-0.040558387', '0.186528497', '0.583333333', '1.394448', '27.092134', '0.204301075', '0.759856631', '0.39841375', '0.719298246', '2.0916722', '-3.2557302', '16.25994589', '0.97175264', '13.00421524', '0.94168055', '15.80064536', '12.24581623']
['107', 'Striker', 'Aaron Schoenfeld', 'Minnesota United', 'Major League Soccer', '1', '1', '2020', 'Israel', 'il', '17/04/1990', '30', 'FALSE', '#5b859b', '#444444', '3298', 'Aaron Schoenfeld', 'Aaron', 'Schoenfeld', '', '91', '193', '17/04/1990', '3529', 'Major League Soccer', '70014', '#5b859b', '#444444', '1044', 'Major League Soccer', '1043', '2020', 'Centre Forward', 'Left Centre Forward', '30:00.0', '4488', '6.1270366', '18', '551.4333', '3', '0', '0.81605524', '0', '0.81605524', '0.17581321', '0', '0', '0', '0.17581321', '1.3056883', '1', '0.32642207', '0', '2.1217434', '0', '0.32642207', '2.4481657', '-0.3551274', '0.16321103', '3.427432', '0.51833844', '0.0625', '0.32642207', '0.16321103', '1', '0.375', '2.6113765', '0.035422343', '0.34252524', '0.131166548', '0', '0', '0', '12.2408285', '64.424065', '0.031746032', '0.16321103', '2.4481657', '0.4896331', '0.06624432', '0.32876137', '0.520833333', '4.080276', '0.16321103', '0', '0', '1.6321105', '0.4571885', '0.78594977', '0.8', '0.65284413', '1.1424773', '65.989815', '0.16321103', '2.2849545', '2.1217434', '0.9285714', '7.815124', '2.1217434', '9.9558735', '7.9973407', '0.8032787', '0', '0', '0.2846154', '0.14615385', '4.569909', '0.23470242', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '6.854864', '0', '0.4896331', '0', '9.629452', '0', '', '0', '0', '9.629452', '18.606058', '0.81578946', '3.8142562', '1.1424773', '0.52096015', '0.90446323', '0.19047619', '0.071428571', '0.738095238', '0.169230769', '0.161538462', '0.669230769', '62.759506', '-0.02912088', '0.185185185', '0.25', '0.16321103', '20.56459', '0.430769231', '0.707692308', '0.32642207', '0.678571429', '0.4896331', '-0.59360296', '12.83796481', '0.89078957', '12.24436188', '0.8558459', '11.43592503', '10.47928715']
['107', 'Striker', 'Abdel Rahman Attef', 'Ghazl El Mehalla', 'Premier League', '1', '1', '2020/2021', 'Egypt', 'eg', '04/06/2001', '19', 'FALSE', '#B30014', '#E5C026', '14124815', 'Abdel Rahman Attef', '', '', '', '', '', '04/06/2001', '865', 'Premier League', '934113', '#B30014', '#E5C026', '1227', 'Premier League', '1090', '2020/2021', 'Centre Forward', 'Left Centre Forward', '00:00.0', '132807', '5.7022223', '7', '513.2', '6', '0', '0.70148087', '0', '0.70148087', '0.021753822', '0', '0', '0', '0.021753822', '1.2275916', '0.5', '1.7537022', '0.8768511', '2.279813', '0.17537022', '0.8768511', '3.5074043', '-0.35825083', '0.35074043', '2.8059235', '0.70899135', '0.166666667', '0.35074043', '0.35074043', '', '0.333333333', '2.1044426', '0.042145594', '0.6872375', '0.326565087', '0', '0', '0', '12.626656', '69.46919', '0', '0', '2.6305532', '0.17537022', '0', '0.111946836', '0.5', '1.2275916', '0.35074043', '0', '0', '1.4029617', '0.52526623', '0.63721305', '0.666666667', '0.70148087', '0.8768511', '71.01409', '0.52611065', '1.2275916', '1.2275916', '1', '7.920317', '2.4551833', '10.522213', '9.645363', '0.9166667', '0', '0', '0.17105263', '0.05263158', '1.9816836', '0.14848882', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '1', '5.4364767', '0', '0', '0', '8.768512', '0', '', '0.17537022', '0', '8.768512', '14.555729', '0.686747', '5.0249157', '0.70148087', '0.37650868', '0.76077986', '0.290322581', '0', '0.709677419', '0.289473684', '0.065789474', '0.644736842', '66.53669', '-0.22697368', '0.218181818', '0.666666667', '0.35074043', '10.697583', '0.210526316', '0.789473684', '0', '0.5625', '0.52611065', '-4.3705444', '15.92864027', '1.0228324', '11.55809593', '0.70122063', '16.29232992', '8.104775429']

In [6]:
# Store File In Variable, Read File
fwd_data = pd.read_csv('Celtic Technical StatsBomb Data.csv')

# Show Df
fwd_data

,Account,Default Radar Template,Name,Team,Competition,Competition Type,Competition Rank,Season,Nationality,Country Code,Date of Birth,Age,Woman Player?,Team Color 1,Team Color 2,Player Id,Player Name,First Name,Last Name,Nickname,Weight,Height,Birth Date,Country Id,Country,Team Id,Team Color 1st,Team Color 2nd,Competition Id,Competition Name,Season Id,Seasons,Primary Position,Secondary Position,Most Recent Match,Player SBData Id,90s Played,Appearances,Minutes Played,Starting Appearances,Assists,Key Passes,Open Play Assists,Open Play Key Passes,Open Play xG Assisted,Set Piece Assists,Set Piece Key Passes,Set-Piece xG Assisted,xG Assisted,Dispossessed,Dribble%,Dribbles,Failed Dribbles,Fouls Won,Penalty wins,Successful Dribbles,Turnovers,Over/Underperformance,Scoring Contribution,Shots & Key Passes,xG & xG Assisted,Goal Conversion%,Goals & Penalty Goals,Non-Penalty Goals,Penalty Conversion%,Shooting%,Shots,Shot Touch%,xG,xG/Shot,Red Cards,Second Yellow Cards,Yellow Cards,Aggressive Actions,Average Defensive Action Distance,Blocks/Shot,Clearances,Defensive Action Regains,Interceptions,PAdj Clearances,PAdj Interceptions,Aerial Win%,Aerial Wins,Dribbled Past,Dribbles Successfully Defended%,Errors,Fouls,PAdj Tackles,PAdj Tackles & Interceptions,Tack/Dribbled Past%,Tackles,Tackles & Interceptions,Average Pressure Distance,Counterpressure Regains,Counterpressures,Counterpressures in Opposing Half,Counterpressures in Opposing Half%,PAdj Pressures,Pressure Regains,Pressures,Pressures in Opposing Half,Pressures in Opposing Half%,Claims - CCAA%,Goalkeeper Aggressive Distance,Pass into Danger%,Pass into Pressure%,Positive Outcome,Positive Outcome%,All Shots Faced,Expected Save%,Goals Conceded,Goals Saved Above Average,Positioning Error,PSxG Faced,Save%,Shots Faced,Shots Faced On Target%,Shot Stopping%,xG Faced,Crossing%,Open Play Final Third Passes,OP Passes Into Box,Passes Inside Box,Passes Into Box,Passes + Touches In Box,Set Piece Passes Into Box,Successful Box Cross%,Successful Crosses,Throughballs,Touches In Box,Carries,Carry%,Carry Length,Deep Progressions,xGBuildup,xGChain,Final Third Pass Backward%,Final Third Pass Forward%,Final Third Pass Sideways%,Pass Backward%,Pass Forward%,Pass Sideways%,Average Pass Distance,Being Pressured Change in Pass%,Left to Right Footedness%,Long Ball%,Long Balls,Open Play Passes,Passes Being Pressured%,Passing%,Pressured Long Balls,Pressured Pass%,Unpressured Long Balls,Being Pressured Change in Pass Length,Pass Length,Pass Length Ratio,Pressured Pass Length,Pressured Pass Length Ratio,Successful Pass Length,Successful Pressured Pass Length
0,107,Striker,Aaron Connolly,Brighton Hove Albion,Premier League,1,1,2020/2021,Republic of Ireland,ie,28/01/2000,21,False,#005daa,#959595,3920732,Aaron Connolly,Aaron,Connolly,Aaron Connolly,NaN,NaN,28/01/2000,1166,Premier League,199,#005daa,#959595,1002,Premier League,1090,2020/2021,Centre Forward,Left Centre Forward,00:00.0,24835,9.571667,17,861.45000,9,0.000000,0.522375,0.000000,0.522375,0.019416,0.000000,0.000000,0.000000,0.019416,1.567125,0.800000,1.044750,0.208950,1.671600,0.104475,0.835800,3.238725,-0.175996,0.208950,2.925300,0.384946,0.086957,0.208950,0.208950,NaN,0.347826,2.402925,0.045549,0.365530,0.152119,0.0,0.0,0.000000,14.417552,62.083176,0.012048,0.104475,2.925300,0.000000,0.129691,0.000000,0.268293,1.149225,0.417900,0.400000,0.0,0.731325,1.016085,1.016085,0.636364,0.731325,0.731325,63.626110,0.208950,2.193975,2.089500,0.952381,14.929437,2.402925,12.954902,9.925126,0.766129,0,0,0.158416,0.108911,2.256660,0.147541,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.000000,3.865576,0.104475,0.000000,0.104475,11.074351,0.000000,0.000000,0.000000,0.000000,10.969876,12.954902,0.717742,6.451850,1.044750,0.368357,0.534279,0.243243,0.054054,0.702703,0.306931,0.108911,0.584158,62.931470,0.081458,0.130435,0.500000,0.104475,9.507226,0.217822,0.782178,0.208950,0.863636,0.104475,-0.957533,13.867809,1.043841,12.910275,0.866283,14.475793,11.183948
1,107,Striker,Aaron Collins,Forest Green Rovers,League Two,1,4,2020/2021,Wales,gb-wls,27/05/1997,24,False,#9bee7c,#fd57ad,636438,Aaron Collins,Aaron,Collins,NaN,74.0,178.0,27/05/1997,979,League Two,480857,#9bee7c,#fd57ad,1005,League Two,1090,2020/2021,Left Centre Forward,Right Centre Forward,30:00.0,9806,41.697598,46,3752.78400,38,0.167875,1.199110,0.143893,0.911323,0.114748,0.023982,0.287786,0.021713,0.136461,2.110433,0.504673,2.566095,1.271056,1.271056,0.023982,1.295039,3.861133,-0.123171,0.335751,4.292813,0.458921,0.054264,0.263804,0.167875,1.000000,0.279070,3.093703,0.040569,0.322460,0.104231,0.0,0.0,0.143893,14.461264,57.801350,0.016216,0.575573,1.990522,0.455662,0.553607,0.467552,0.211538,0.791413,0.743448,0.256410,0.0,0.839377,0.816456,1.284008,0.530303,0.839377,1.295039,59.988820,0.167875,2.733970,2.278309,0.833333,13.067722,1.702736,12.854457,8.969341,0.697761,0,0,0.190563,0.078040,5.324048,0.339709,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.293333,10.120487,0.887341,0.455662,1.151145,7.626339,0.263804,0.229167,0.527608,0.167875,6.738997,26.596256,0.791704,6.973400,4.052991,0.458038,0.651816,0.151659,0.206161,0.642180,0.187840,0.204174,0.607985,66.791670,-0.054411,0.206278,0.444444,1.822647,22.087603,0.185118,0.652450,1.007252,0.598039,3.669276,-3.607311,20.804843,0.905465,17.197533,0.947914,18.838051,16.301781
2,107,Striker,Aaron Drinan,Ipswich Town,League One,1,3,2020/2021,Republic of Ireland,ie,06/05/1998,23,False,#0060aa,#e2192b,5273390,Aaron Drinan,Aaron,Drinan,NaN,NaN,NaN,06/05/1998,1166,League One,111,#0060aa,#e2192b,1004,League One,1090,2020/2021,Centre Forward,Left Centre Forward,00:00.0,47357,9.127778,22,821.50006,6,0.000000,1.095557,0.000000,1.095557,0.124516,0.000000,0.000000,0.000000,0.124516,1.752891,0.461538,1.424224,0.766890,0.547778,0.000000,0.657334,3.834449,-0.179104,0.109556,2.410225,0.288660,0.083333,0.109556,0.109556,NaN,0.416667,1.314668,0.013413,0.164144,0.124856,0.0,0.0,0.219111,25.197805,63.519800,0.009709,0.657334,3.177115,0.876445,0.609985,0.581655,0.316239,4.053560,0.438223,0.000000,0.0,1.643335,0.841039,1.422694,0.636364,0.766890,1.643335,65.143560,0.328667,4.491783,4.382227,0.975610,21.695127,2.410225,22.787580,18.076687,0.793269,0,0,0.307692,0.112821,3.242848,0.289345,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.400000,8.435787,0.328667,0.766890,0.328667,11.393790,0.000000,0.333333,0.438223,0.109556,11.065124,17.638466,0.751553,5.476466,1.095557,0.397302,0.450145,0.233766,0.090909,0.675325,0.189744,0.164103,0.646154,67.543080,-0.203911,0.198113,0.333333,0.219111,21.144247,0.302564,0.661538,0.657334,0.457627,0.657334,-1.079741,13.122970,0.953346,12.043229,0.992277,12.510730,11.950219
3,107,Striker,Aaron Jarvis,Scunthorpe United,League Two,1,4,2020/2021,England,gb-eng,21/08/1998,22,False,#00acdd,#a83249,6794672,Aaron Jarvis,NaN,NaN,NaN,80.0,188.0,21/08/1998,618,League Two,158,#00acdd,#a83249,1005,League Two,1090,2020/2021,Centre Forward,Right Centre Forward,00:00.0,15276,7.280370,13,655.23334,6,0.000000,0.412067,0.000000,0.412067,0.024662,0.000000,0.000000,0.000000,0.024662,0.412067,0.250000,0.549423,0.412067,1.785623,0.000000,0.137356,5.494226,-0.124091,0.274711,2.197691,0.398803,0.153846,0.274711,0.274711,NaN,0.307692,1.785623,0.018480,0.374141,0.209529,0.0,0.0,0.274711,11.125808,58.299210,0.000000,0.824134,1.785623,0.137356,0.595767,0.211697,0.342857,4.944803,0.274711,0.500000,0.0,1.922979,0.503878,0.715575,0.714286,0.686778,0.824134,61.816060,0.137356,1.373557,0.824134,0.600000,7.691807,1.373557,8.516050,6.181005,0.725807,0,0,0.277778,0.095238,1.813095,0.182825,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,NaN,5.906292,0.137356,0.274711,0.137356,8.653406,0.000000,0.000000,0.000000,0.000000,8.516050,15.246477,0.675676,4.087920,1.098845,0.347094,0.476982,0.232558,0.046512,0.720930,0.190476,0.126984,0.682540,63.982933,-0.014096,0.163636,0.333333,0.137356,17.032100,0.531746,0.611111,1.098845,0.597015,0.137356,-0.140726,15.322452,0.918077,15.181726,0.827747,14.067189,12.566622
4,107,Striker,Aaron Leya Iseka,Metz,Ligue1,1,1,2020/2021,Belgium,be,15/11/1997,23,False,#b0053a,#959595,14201,Aaron Leya Iseka,Aaron,Leya Iseka,NaN,78.0,180.0,15/11/1997,483,Ligue1,506,#b0053a,#959595,1007,Ligue 1,1090,2020/2021,Centre Forward,Left Centre Forward,00:00.0,9936,11.810740,21,1062.96670,12,0.000000,1.016024,0.000000,1.016024,0.060223,0.000000,0.000000,0.000000,0.060223,1.693374,0.608696,1.947380,0.762018,1.100693,0.000000,1.185362,3.471417,-0.092216,0.169337,2.540061,0.261553,0.111111,0.338675,0.169337,0.666667,0.333333,1.524037,0.017356,0.201330,0.132103,0.0,0.0,0.338675,13.377654,60.321053,0.021739,0.338675,1.693374,0.169337,0.256728,0.122356,0.364865,2.286055,0.592681,0.300000,0.0,2.370723,0.538255,0.660611,0.562500,0.762018,0.931356,64.370125,0.169337,2.540061,2.201386,0.866667,7.847730,0.931356,10.244912,8.212863,0.801653,0,0,0.186869,0.111111,2.573928,0.166758,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.000000,5.080121,0.169337,0.084669,0.169337,10.583587,0.000000,0.000000,0.000000,0.254006,10.414249,17.357082,0.760976,5.144907,2.032049,0.231556,0.387038,0.216667,0.116667,0.666667,0.196970,0.111111,0.691919,57.748350,-0.108081,0.097744,0.555556,0.423343,16.087051,0.277778,0.762626,0.423343,0.654545,0.677350,-0.520735,15.330923,0.974999,14.810187,0.993469,14.947639,14.713459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1653,107,Striker,An Medved,Slovan Bratislava,Super Liga,1,1,2020/2021,Slovenia,si,14/06/1999,21,False,#EF2E24,#2EB1E6,14101778,An Medved,NaN,NaN,NaN,NaN,NaN,14/06/1999,571,Super Liga,440387,#EF2E24,#2EB1E6,1124,Super Liga,1090,2020/2021,Centre Forward,Left Centre Forward,15:00.0,43980,9.986482,18,898.78330,9,0.100135,0.901218,0.100135,0.901218,0.100268,0.000000,0.000000,0.000000,0.100268,1.001354,0.250000,0.400541,0.300406,2.202978,0.000000,0.100135,1.401895,-0.008160,0.500677,3.304467,0.508837,0.166667,0.400541,0.400541,NaN,0.416667,2.403249,0.033688,0.408569,0.170007,0.0,0.0,0.100135,11.415432,57.297300,0.018349,1.101489,2.303113,0.200271,1.110981,0.243521,0.563380,4.005415,0.700948,0.333333,0.0,1.101489,0.783651,1.027173,0.533333,0.801083,1.001354,63.728140,0.200271,2.403249,2.403249,1.000000,12.433667,1.902572,9.713131,7.910694,0.814433,0,0,0.259669,0.110497,2.663600,0.150452,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.666667,7.009476,0.600812,0.100135,0.600812,12.116379,0.000000,0.000000,0.200271,0.200271,11.515567,13.318005,0.827068,4.095230,1.502031,0.566895,0.896257,0.185714,0.214286,0.600000,0.176796,0.209945,0.613260,64.946526,-0.147860,0.176471,0.400000,0.200271,17.423555,0.325967,0.707182,1.201624,0.559322,0.400541,-1.009345,13.129701,0.963920,12.120357,1.024970,12.655987,12.423001
1654,107,Striker,An Medved,Wisa Krakw,Ekstraklasa,1,1,2020/2021,Slovenia,si,14/06/1999,21,False,#da251c,#01478f,14101778,An Medved,NaN,NaN,NaN,NaN,NaN,14/06/1999,571,Ekstraklasa,427303,#da251c,#01478f,1038,Ekstraklasa,1090,2020/2021,Centre Forward,Right Centre Forward,00:00.0,43980,6.450185,13,580.51666,5,0.155034,0.465103,0.155034,0.465103,0.015951,0.000000,0.000000,0.000000,0.015951,1.240274,0.636364,1.705377,0.620137,1.395309,0.000000,1.085240,3.720823,-0.102681,0.155034,2.015446,0.257715,0.000000,0.000000,0.000000,NaN,0.400000,1.550343,0.022284,0.241764,0.155942,0.0,0.0,0.155034,18.914186,57.695263,0.000000,1.395309,3.410755,0.775172,1.328212,0.734396,0.514286,5.581235,0.465103,0.400000,0.0,1.860412,0.725601,1.459997,0.666667,0.930206,1.705377,60.458280,0.000000,1.705377,1.705377,1.000000,13.036865,2.635583,16.123568,11.472539,0.711538,0,0,0.285714,0.109244,1.767391,0.124863,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.333333,4.185926,0.310069,0.000000,0.310069,8.681922,0.000000,0.000000,0.155034,0.000000,8.371853,14.263156,0.750000,4.911600,1.085240,0.285139,0.330810,0.148148,0.259259,0.592593,0.142857,0.268908,0.588235,57.902260,-0.199631,0.193548,0.454545,0.775172,16.278603,0.344538,0.638655,1.860412,0.439024,1.240274,-1.512323,17.285965,0.963502,15.773642,1.050401,16.655060,16.568645
1655,107,Striker,Eljko Dimitrov,Inija,Super Liga,1,1,2020/2021,Serbia,rs,19/02/1994,27,False,#3A9A74,#961F23,14112505,Eljko Dimitrov,NaN,NaN,NaN,80.0,183.0,19/02/1994,20,Super Liga,903946,#3A9A74,#961F23,1079,Super Liga,1090,2020/2021,Centre Forward,Right Centre Forward,00:00.0,86861,15.857964,19,1427.21680,16,0.000000,0.882837,0.000000,0.819777,0.072118,0.000000,0.063060,0.001936,0.074054,1.576495,0.466667,0.945897,0.504478,2.017914,0.000000,0.441419,2.522392,-0.276925,0.189179,3.089930,0.466105,0.085714,0.252239,0.189179,1.000000,0.371429,2.207093,0.033526,0.392051,0.177632,0.0,0.0,0.063060,17.278383,66.174820,0.000000,0.441419,2.207093,0.189179,0.360321,0.157018,0.361111,2.459332,0.441419,0.222222,0.0,2.080973,0.201569,0.358587,0.363636,0.252239,0.441419,68.232796,0.126120,3.152990,2.711571,0.860000,14.345790,1.765674,14.945172,12.548900,0.839662,0,0,0.262357,0.133080,2.572840,0.160377,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.250000,4.161946,0.189179,0.252239,0.378359,10.657105,0.189179,0.000000,0.063060,0.000000,10.467926,11.792182,0.705882,4.832650,1.324256,0.385471,0.572204,0.121212,0.242424,0.636364,0.193916,0.224335,0.581749,60.147270,-0.054744,0.131387,0.363636,0.252239,13.494796,0.315589,0.669202,0.504478,0.614458,0.630598,-2.528044,15.469689,0.977532,12.941645,0.952425,15.122115,12.325945
1656,107,Striker,Zinho Gano,Kortrijk,Jupiler Pro League,1,1,2020/2021,Belgium,be,13/10/1993,27,False,#ff0000,#525b6b,16376,Zinho Gano,Zinho,Gano,NaN,86.0,193.0,13/10/1993,483,Jupiler Pro League,607,#ff0000,#525b6b,1046,Jupiler Pro League,1090,2020/2021,Left Centre Forward,Right Centre Forward,00:00.0,20840,9.437778,11,849.40000,9,0.105957,0.635743,0.105957,0.635743,0.050560,0.000000,0.000000,0.000000,0.050560,1.695314,0.454545,2.331057,1.271486,0.847657,0.000000,1.059572,6.251472,0.254501,0.741700,2.860843,0.487198,0.285714,0.635743,0.635743,NaN,0.523810,2.225100,0.021994,0.436639,0.196233,0.0,0.0,0.000000,16.211443,58.087480,0.029412,1.059572,2.648928,0.529786,0.956900,0.590724,0.561798,5.297857,0.635743,0.166667,0.0,1.483400,0.314295,0.905019,0.250000,0.211914,0.741700,63.060390,0.000000,2.966800,2.648928,0.892857,11.586734,1.695314,14.516129,10.277843,0.708029,0,0,0.224771,0.105505,2.140334,0.129904,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.333333,4.662115,0.000000,0.423829,0.000000,12.291028,0.000000,NaN,0.105957,0.000000,12.291028,19.708029,0.634409,5.098627,1.377443,0.525737,0.643460,0.181818,0.090909,0.727273,0.224771,0.169725,0.605505,57.543854,-0.140907,0.760684,0.333333,0.211914,20.767601,0.389908,0.646789,1.271486,0.505882,0.423829,-1.729191,14.247569,0.975474,12.518378,0.841116,13.898138,10.529402
1657,107,Striker,Zuberu Sharani,Zempln Michalovce,Super Liga,1,1,2020/2021,Ghana,gh,07/01/2000,21,False,#FCF002,#30348F,14102016,Zuberu Sharani,NaN,NaN,NaN,0.0,183.0,07/01/2000,227,Super Liga,933773,#FCF002,#30348F,1124,Super Liga,1090,2020/2021,Centre Forward,Left Wing,00:00.0,44319,7.018889,11,631.70000,6,0.000000,1.282254,0.000000,1.282254,0.163907,0.000000,0.000000,0.000000,0.163907,2.137090,0.705882,2.422036,0.712363,1.567200,0.000000,1.709672,3.276872,-0.092407,0.284945,2.991926,0.377353,0.166667,0.284945,0.284945,NaN,0.416667,1.709672,0.022500,0.213446,0.124846,0.0,0.0,0.142473,13.819851,55.500916,0.000000,0.854836,2.279563,0.427418,0.842713,0.572614,0.403846,2.991926,0.427418,0.571429,0.0,0.712363,1.218024,1.790639,0.700000,0.997309,1.424727,59.338345,0.142473,2.564508,2.279563,0.888889,14.781947,1.709672,12.110179,8.405889,0.694118,0,0,0.279412,0.139706,4.616115,0.277873,0.0,0,0,0,0,0,0,0,NaN,NaN,0.0,0.142857,7.551053,0.142473,0.712363,0.142473,11.255342,0.000000,0.000000,0.142473,0.284945,11.112870,20.658540,0.765517,5.772531,2.137090,0.294936,0.551885,0.283019,0.113208,0.603774,0.198529,0.147059,0.654412,64.531520,-0.103935,0.761905,0.500000,0.284945,17.951560,0.272059,0.698529,0.854836,0.594595,0.569891,-3.372253,14.656555,0.992804,11.284303,0.957866,14.551084,10.808850

---

### Find Top 5 Players

# Goal Scorer In The Box (Indexing)

### Touches In The Box

In [7]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
top_tch_in_bx = fwd_data.sort_values(by=['Touches In Box'], ascending = [False])
top_tch_in_bx

# Create Variable And Use Above To Find Top 5 Results
top_plyr_tch_in_bx = top_tch_in_bx.head(5)

# Call Variable Of Top 5 And Only Show Selected Columns
top_plyr_tch_in_bx[['Name','Team','Primary Position','Touches In Box']]

,Name,Team,Primary Position,Touches In Box
1616,Walter Bwalya,Al Ahly SC,Centre Forward,22.018236
1286,Patrik Schick,Bayer Leverkusen,Centre Forward,21.676384
1154,Milan Pavkov,FKCrvena Zvezda,Centre Forward,20.902372
1166,Munas Dabbur,Hoffenheim,Left Centre Forward,19.864437
1330,Rafael Santos Borr Amaury,River Plate,Centre Forward,19.792873

### Touches In Box Percentile Ranks

In [8]:
# Select Numeric Columns Only
numeric_columns = top_plyr_tch_in_bx.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
tch_in_bx_percentile_rank = numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
tch_in_bx_percentile_rank['Name'] = top_plyr_tch_in_bx['Name']
tch_in_bx_percentile_rank['Team'] = top_plyr_tch_in_bx['Team']
tch_in_bx_percentile_rank['Primary Position'] = top_plyr_tch_in_bx['Primary Position']

# Create New Df With Player And Percentile Rank
tch_in_bx_percentile_rank = tch_in_bx_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins','Aerial Win%','Open Play Final Third Passes','OP Passes Into Box',
                   'Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
tch_in_bx_percentile_rank.iloc[:, 3:] = tch_in_bx_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
tch_in_bx_percentile_rank.iloc[:, 3:] = tch_in_bx_percentile_rank.iloc[:, 3:].astype(int)
tch_in_bx_percentile_rank[['Name','Team','Primary Position','Touches In Box',]]

,Name,Team,Primary Position,Touches In Box
1616,Walter Bwalya,Al Ahly SC,Centre Forward,100.0
1286,Patrik Schick,Bayer Leverkusen,Centre Forward,80.0
1154,Milan Pavkov,FKCrvena Zvezda,Centre Forward,60.0
1166,Munas Dabbur,Hoffenheim,Left Centre Forward,40.0
1330,Rafael Santos Borr Amaury,River Plate,Centre Forward,20.0

### Goals And Penalty Goals

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
top_gls = fwd_data.sort_values(by=['Goals & Penalty Goals'], ascending = [False])
top_gls

# Create Variable And Use Above To Find Top 5 Results
top_plyr_gls = top_gls.head(5)

# Replace NaN & inf To 0
top_plyr_gls.iloc[:, 1:] = top_plyr_gls.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable Of Top 5 And Only Show Selected Columns
top_plyr_gls[['Name','Team','Primary Position','Goals & Penalty Goals']]

### Goals & Penalty Goals Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_gls.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
gls_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
gls_percentile_rank['Name'] = top_plyr_gls['Name']
gls_percentile_rank['Team'] = top_plyr_gls['Team']
gls_percentile_rank['Primary Position'] = top_plyr_gls['Primary Position']

# Create New Df With Player And Percentile Rank
gls_percentile_rank = gls_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins',
                                           'Aerial Win%','Open Play Final Third Passes','OP Passes Into Box','Passes + Touches In Box',
                                           'Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
gls_percentile_rank.iloc[:, 3:] = gls_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
gls_percentile_rank.iloc[:, 3:] = gls_percentile_rank.iloc[:, 3:].astype(int)
gls_percentile_rank[['Name','Team','Primary Position','Goals & Penalty Goals']]

# Plots

In [ ]:
# Plot Figure Size
plt.figure(figsize = (10, 6))

# Create Axes Variable
ax = plt.axes()

# Set The Background Color
ax.set_facecolor('#018749')

# Add Team Name Column To X-label Using String Concatination
players_team = top_plyr_gls['Name'] + '\n ('+ top_plyr_gls ['Team'] + ')'

# Plot Data
# Inside () Call The Previous List, Df, Then Columns Required, Set Marker o, Line Type -- & Color w, Marker Size (ms) And Marker Edge Color (mec)
plt.plot(players_team, top_plyr_gls['Touches In Box'],'o--w', ms=6, mec='w')


# Set Top Player
top_player =  1
# Change Chosen Player Point Stylings
plt.scatter(players_team.iloc[top_player], top_plyr_gls['Touches In Box'].iloc[top_player],
           marker = '*', s=300, color='yellow', edgecolor='w', zorder=5)


# Name Labels And Font Weight 
plt.xlabel('Top 5 Players', fontweight = 'bold')
plt.ylabel('Touches In Box', fontweight = 'bold')
plt.title('Number Of Touches In The Box', fontweight = 'bold')

# Show Grid
plt.grid(True)

# Plot xticks Function & Rotate *rotation* And Move Labels To The Right *ha* (horizontal axis)
plt.xticks(rotation=45, ha = 'right')

# Displays Figure
plt.show()

In [ ]:
# Create Variable Using Df Add Columns To Use. Add .copy() To Make A New df *[[]]* From Columns In Df So Any Changes Dont Affect Original Df
gls_plot= top_plyr_gls[['Name','Team','Goals & Penalty Goals']].copy()

# Combine Team Name With Players On Xlabel With String Concatination. 
# Create A New Column & Name It. 
# Call Df & Name Column. Use + To Combine The Team Column. 
# Use ''. Inside Use (), And Inside That Open Another '' Then Inside Use + Call Df and Team Column Then Close + 
gls_plot['Players Team']= gls_plot['Name'] + ' \n(' + gls_plot['Team'] +  ')'

# Plot Figure Size
plt.figure(figsize=(10,8))

# Plot Axes.
ax=plt.axes()

# Set The Background Color. (Hex Number)
ax.set_facecolor('#018749')

# Plot Bars.
# Create A Variable To Store The Bars Of The Graph. Plot The bars Inside () With Combine Df, Combined Column (Players_Team) & KPI Column & Change Bar Color.
bars=plt.bar(gls_plot['Players Team'], gls_plot['Goals & Penalty Goals'], color='white')

# Mark Top Player
tp_plyr = 0

# Style Bar Style
bars[tp_plyr].set_color('gold')

# Annotate Bars. 
# Create ax.bar_label Function, In () Call The bars Variable To Use Stored Data, 
# Then Make A labels Variable. Create A Series *[]* & Use An fstring Followed By {} *To Indicate Sets (several items in a single variable) & Dictionary Literals (1+ key/pair items)*, 
# Add val, To Get The Value Followed By : Then .2f *String Formatting* To Declare That The Value Stops After 2 Decimal Places 
# Create A List Comprehension With df & KPI Column *Run Through Every Value (val) In The KPI Column*,  
# Followed By label_type Location *Chooses Placement Of Data On Bar*, And Fontweight.
# Add Axis Labels, Color & Fontweight
ax.bar_label(bars, labels=[f"{val:.2f}" for val in gls_plot['Goals & Penalty Goals']], label_type='center', fontweight='bold')

# Add Axis Labels, Color & Fontweight
plt.title('Players Goals & Penalty Goals', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Goals And Pen Goals', fontweight='bold')

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

# Strong In The Air (Indexing)

### Aerial Wins

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
hder_stats = fwd_data.sort_values(by=['Aerial Wins'], ascending = [False])
hder_stats

# Create Variable And Use Above To Find Top Results
top_plyr_hder_stats = hder_stats.head(5)

# Replace NaN & inf To 0
top_plyr_hder_stats.iloc[:, 1:] = top_plyr_hder_stats.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable Of Top Results And Only Show Selected Columns
top_plyr_hder_stats[['Name','Team','Primary Position','Aerial Wins']]

## Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_hder_stats.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
hder_stats_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
hder_stats_percentile_rank['Name'] = top_plyr_hder_stats['Name']
hder_stats_percentile_rank['Team'] = top_plyr_hder_stats['Team']
hder_stats_percentile_rank['Primary Position'] = top_plyr_hder_stats['Primary Position']

# Create New DataFrame With Player & Percentile Rank
hder_stats_percentile_rank = hder_stats_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins',
                                                         'Aerial Win%','Open Play Final Third Passes','OP Passes Into Box','Passes + Touches In Box',
                                                         'Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
hder_stats_percentile_rank.iloc[:, 3:] = hder_stats_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
hder_stats_percentile_rank.iloc[:, 3:] = hder_stats_percentile_rank.iloc[:, 3:].astype(int)
hder_stats_percentile_rank[['Name','Team','Primary Position','Touches In Box',]]

### Aerial Win%

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
hder_perc_stats = cntr_fwds.sort_values(by=['Aerial Win%'], ascending = [False])
hder_perc_stats

# Create Variable And Use Above To Find Top 5 Results
top_plyr_hder_perc_stats = hder_perc_stats.head(5)

# Call Variable Of Top 5 And Only Show Selected Columns
top_plyr_hder_perc_stats[['Name','Team','Primary Position','Aerial Win%']]

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_hder_perc_stats.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
hder_perc_stats_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New DataFrame
hder_perc_stats_percentile_rank['Name'] = top_plyr_hder_perc_stats['Name']
hder_perc_stats_percentile_rank['Team'] = top_plyr_hder_perc_stats['Team']
hder_perc_stats_percentile_rank['Primary Position'] = top_plyr_hder_perc_stats['Primary Position']

# Create New Df With Player And Percentile Rank
hder_perc_stats_percentile_rank = hder_perc_stats_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals',
                                                                   'Aerial Wins','Aerial Win%','Open Play Final Third Passes','OP Passes Into Box',
                                                                   'Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
hder_perc_stats_percentile_rank.iloc[:, 3:] = hder_perc_stats_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
hder_perc_stats_percentile_rank.iloc[:, 3:] = hder_perc_stats_percentile_rank.iloc[:, 3:].astype(int)
hder_perc_stats_percentile_rank[['Name','Team','Primary Position','Aerial Win%']]

# Plots

In [ ]:
# Plot Figure Size.
plt.figure(figsize=(10,8))

# Plot Axes
ax = plt.axes()

# Set The Background Color. (Hex Number)
ax.set_facecolor('#018749')

# Add Team Names Column To X-label Using String Concatination
players_team = top_plyr_hder_perc_stats['Name'] + '\n ('+ top_plyr_hder_perc_stats['Team'] + ')'

# Plot Data.
# Call Plot Function. Inside () Call The Previous List *For Data Stored*, Df With KPI Columns, Set Marker *o*, Line Type *--* & Color *w*, Marker Size *ms* And Marker Edge Color *mec*
plt.plot(players_team, top_plyr_hder_perc_stats['Aerial Wins'],'o--w', ms=6, mec='w')

# Set Top Player
tp_plyr = 2

# Change Chosen Player Point Stylings
plt.scatter(players_team.iloc[tp_plyr], top_plyr_hder_perc_stats['Aerial Wins'].iloc[tp_plyr],
           marker='*', s=300, color='yellow', edgecolor='w', zorder=5)


# Name Labels And Font Weight 
plt.title('Players Aerial Wins', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Aerial Wins', fontweight='bold')

# Show Grid
plt.grid(axis='x', color='black', linewidth = 1.5)

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

In [ ]:
# Create Variable Using Df And Columns To Use. Add .copy() To Make A New Df *[[]]* From Columns In Df So Any Changes Dont Affect Original Df.
awp_plot= top_plyr_hder_perc_stats[['Name','Team','Aerial Win%']].copy()

# Combine Team Name With Players On Xlabel With String Concatination. 
# Create A New Column & Name It. 
# Call Df & Name Column. Use + To Combine The Team Column. 
# Use ''. Inside Use (), And Inside That Open Another '' Then Inside Use + Call Df and Team Column Then Close + .
awp_plot['Players Team']= awp_plot['Name'] + '\n (' + awp_plot['Team'] +  ')'

# Plot Figure Size.
plt.figure(figsize=(10,8))

# Plot Axes.
ax=plt.axes()

# Set Background Color. (Hex Number)
ax.set_facecolor('#018749')

# Plot Bars.
# Create A Variable To Store The Bars Of The Graph. Plot The bars Inside () With Combine Df, Combined Column (Players_Team) & KPI Column & Change Bar Color.
bars=plt.bar(awp_plot['Players Team'], awp_plot['Aerial Win%'], color='white')

# Set Top Player
tp_plyr = 0
# Set Bar Color
bars[tp_plyr].set_color('gold')

# Annotate Bars. 
# Create ax.bar_label Function, In () Call The bars Variable To Use Stored Data, 
# Then Make A labels Variable. Create A Series *[]* & Use An fstring Followed By {} *To Indicate Sets (several items in a single variable) & Dictionary literals (1+ key/pair items)*, 
# Add val, To Get The Value Followed By : Then .2f *String Formatting* To Declare That The Value Stops After 2 Decimal Places 
# Create A List Comprehension With df & KPI Column *Run Through Every Value (val) In The KPI Column*,  
# Followed By label_type Location *Chooses Placement Of Data On Bar*, And Fontweight.
# Add Axis Labels, Color & Fontweight
ax.bar_label(bars, labels=[f"{val:.2f}" for val in awp_plot['Aerial Win%']], label_type='center', fontweight='bold')

# Add Axis Labels, Color & Fontweight
plt.title('Players Aerial Wins Percentage', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Aerial Win %', fontweight='bold')

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

# Good Link Up Play (Indexing)

### Open Play Final Third Passes

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
opn_ply_fnl_trd_ps = cntr_fwds.sort_values(by=['Open Play Final Third Passes'], ascending = [False])
opn_ply_fnl_trd_ps

# Create Variable And Use Above To Find Top 5 Results
top_plyr_fnl_trd_ps = opn_ply_fnl_trd_ps.head(5)

# Replace NaN & inf To 0
top_plyr_fnl_trd_ps.iloc[:, 1:] = top_plyr_fnl_trd_ps.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable Of Top 5 And Only Show Selected Columns.
top_plyr_fnl_trd_ps[['Name','Team','Primary Position','Open Play Final Third Passes']]

## Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_fnl_trd_ps.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
fnl_trd_ps_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
fnl_trd_ps_percentile_rank['Name'] = top_plyr_fnl_trd_ps['Name']
fnl_trd_ps_percentile_rank['Team'] = top_plyr_fnl_trd_ps['Team']
fnl_trd_ps_percentile_rank['Primary Position'] = top_plyr_fnl_trd_ps['Primary Position']

# Create New DataFrame With Player & Percentile Rank
fnl_trd_ps_percentile_rank = fnl_trd_ps_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins',
                                                         'Aerial Win%','Open Play Final Third Passes','OP Passes Into Box','Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
fnl_trd_ps_percentile_rank.iloc[:, 3:] = fnl_trd_ps_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
fnl_trd_ps_percentile_rank.iloc[:, 3:] = fnl_trd_ps_percentile_rank.iloc[:, 3:].astype(int)
fnl_trd_ps_percentile_rank[['Name','Team','Primary Position','Open Play Final Third Passes']]

In [ ]:
# Create Variable Using Df And Columns To Use. Add .copy() To Make A New Df *[[]]* From Columns In Df So Any Changes Dont Affect Origianl Df.
ftp_plot = top_plyr_fnl_trd_ps[['Name','Team','Open Play Final Third Passes']].copy()

# Combine Team Name With Players On Xlabel With String Concatination. 
# Create A New Column & Name It For The Teams Name. 
# Call df & Name Column. Use + To Combine The Team Column. 
# Use ''. Inside Use (), And Inside That Open Another '' Then Inside Use + Call df and Team Column Then Close + .
ftp_plot['Players Team'] = ftp_plot['Name'] + '\n (' + ftp_plot['Team']+')'

# Plot Figure Size.
plt.figure(figsize=(10,8))

# Plot Axes.
ax=plt.axes()

# Set The Background Color.In (Hex Number)
ax.set_facecolor('#018749')

# Plot Bars
# Create A Variable To Store The Bars Of The Graph. Plot The bars Inside () With Combine Df, Combined Column (Players_Team) & KPI Column & Change Bar Color.
bars = plt.bar(ftp_plot['Players Team'], ftp_plot['Open Play Final Third Passes'], color='white')

# Mark Top Player
tp_plyr = 0

# Set Bar Color
bars[tp_plyr].set_color('gold')


# Annotate Bars 
# Create ax.bar_label Function, In () Call The bars Variable To Use Stored Data, 
# Then Make A labels Variable. Create A Series *[]* & Use An fstring Followed By {} *To Indicate Sets (several items in a single variable) & Dictionary literals (1+ key/pair items)*, 
# Add val, To Get The Value Followed By : Then .2f *String Formatting* To Declare That The Value Stops After 2 Decimal Places 
# Create A List Comprehension With df & KPI Column *Run Through Every Value (val) In The KPI Column*,  
# Followed By label_type Location *Chooses Placement Of Data On Bar*, And Fontweight.
# Add Axis Labels, Color & Fontweight
ax.bar_label(bars, labels=[f"{val:.2f}" for val in ftp_plot['Open Play Final Third Passes']], label_type='center', fontweight='bold')

# Add Axis Labels, Color & Fontweight
plt.title('Players Open Play Final Third Pass', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Final Third Passes', fontweight='bold')

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

### OP Passes Into Box

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
opn_ply_pass_box = fwd_data.sort_values(by=['OP Passes Into Box'], ascending = [False])
opn_ply_pass_box

# Create Variable And Use Above To Find Top 5 Results
top_plyr_opn_ply_pass_box = opn_ply_pass_box.head(5)

# Replace NaN & inf To 0
top_plyr_opn_ply_pass_box.iloc[:, 1:] = top_plyr_opn_ply_pass_box.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable Of Top 5 And Only Show Selected Columns
top_plyr_opn_ply_pass_box[['Name','Team','Primary Position','OP Passes Into Box']]

## Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_opn_ply_pass_box.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
opn_ply_pass_box_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
opn_ply_pass_box_percentile_rank['Name'] = top_plyr_opn_ply_pass_box['Name']
opn_ply_pass_box_percentile_rank['Team'] = top_plyr_opn_ply_pass_box['Team']
opn_ply_pass_box_percentile_rank['Primary Position'] = top_plyr_opn_ply_pass_box['Primary Position']

# Create New Df With Player & Percentile Rank
opn_ply_pass_box_percentile_rank = opn_ply_pass_box_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins','Aerial Win%',
                                                                     'Open Play Final Third Passes','OP Passes Into Box','Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]
# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
opn_ply_pass_box_percentile_rank.iloc[:, 3:] = opn_ply_pass_box_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
opn_ply_pass_box_percentile_rank.iloc[:, 3:] = opn_ply_pass_box_percentile_rank.iloc[:, 3:].astype(int)
opn_ply_pass_box_percentile_rank[['Name','Team','Primary Position','OP Passes Into Box']]

In [ ]:
# Plot Figure Size.
plt.figure(figsize=(10,8))

# Create Axes Variable
ax= plt.axes()

# Set The Background Color
ax.set_facecolor('#018749')

# Add Team Name Column To X-label Using String Concatination
players_team = top_plyr_opn_ply_pass_box['Name'] + '\n ('+ top_plyr_opn_ply_pass_box ['Team'] + ')'

# Plot Data.
# Call Plot Function. Inside () Call The Previous List *For Data Stored*, Df With KPI Columns, Set Marker *o*, Line Type *--* & Color *w*, Marker Size *ms* And Marker Edge Color *mec*
plt.plot(players_team, top_plyr_opn_ply_pass_box['OP Passes Into Box'],'o--w', ms=8, mec='w')

# Change Marker For Top Player
top_player =  0

# Change Chosen Player Point Stylings
plt.scatter(players_team.iloc[top_player], top_plyr_opn_ply_pass_box['OP Passes Into Box'].iloc[top_player],
           marker = '*', s=200, color='yellow', edgecolor='w', zorder=5)


# Add Axis Labels, Color & Fontweight
plt.title('Open Play Passes Into The Box', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Final Third Box Passes', fontweight='bold')

# Show Grid
plt.grid(axis='y', color='black', linewidth = 1.5)

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

### Passes + Touches In Box

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Uses Df Above To Sorts Values Of The KPI Column In Descending Order
pass_tch_bx = cntr_fwds.sort_values(by=['Passes + Touches In Box'], ascending = [False])
pass_tch_bx

# Create Variable And Use Above To Find Top 5 Results
top_plyr_pass_tch_bx = pass_tch_bx.head(5)

# Call Variable Of Top 5 And Only Show Selected Columns
top_plyr_pass_tch_bx[['Name','Team','Primary Position','Passes + Touches In Box']]

## Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_pass_tch_bx.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
pass_tch_bx_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate player To New Df
pass_tch_bx_percentile_rank['Name'] = top_plyr_pass_tch_bx['Name']
pass_tch_bx_percentile_rank['Team'] = top_plyr_pass_tch_bx['Team']
pass_tch_bx_percentile_rank['Primary Position'] = top_plyr_pass_tch_bx['Primary Position']

# Create New Df With Player And Percentile Rank
pass_tch_bx_percentile_rank = pass_tch_bx_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins','Aerial Win%','Open Play Final Third Passes',
                                                           'OP Passes Into Box','Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]
# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
pass_tch_bx_percentile_rank.iloc[:, 3:] = pass_tch_bx_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
pass_tch_bx_percentile_rank.iloc[:, 3:] = pass_tch_bx_percentile_rank.iloc[:, 3:].astype(int)
pass_tch_bx_percentile_rank[['Name','Team','Primary Position','Passes + Touches In Box']]

# Plots

In [ ]:
# Create Variable Using Df And Columns To Use. Add .copy() To Make A New df *[[]]* From Columns In Df So Any Changes Dont Affect Origianl Df.
ptib_plot = top_plyr_pass_tch_bx[['Name','Team','Passes + Touches In Box']].copy()

# Combine Team Name With Players On Xlabel With String Concatination. 
# Create A New Column & Name It To Hold Data. 
# Call df & Name Column. Use + To Combine The Team Column. 
# Use ''. Inside Use (), And Inside That Open Another '' Then Inside Use + Call df and Team Column Then Close + .
ptib_plot['Players Team'] = top_plyr_pass_tch_bx['Name'] + '\n ('+ top_plyr_pass_tch_bx['Team'] +')'

# Plot Figure Size.
plt.figure(figsize=(10,8))

# Plot Axes.
ax=plt.axes()

# Set The Background Color.(Hex Number)
ax.set_facecolor('#018749')

# Plot Bars.
# Create A Variable To Store The Bars Of The Graph. Plot The bars Inside () With Combine Df, Combined Column (Players_Team) & KPI Column & Change Bar Color.
bars = plt.bar(ptib_plot['Players Team'], ptib_plot['Passes + Touches In Box'], color='white')

# Mark Top Player
tp_plyr = 0
# Set Bar Color
bars[tp_plyr].set_color('gold')

# Annotate Bars. 
# Create ax.bar_label Function, In () Call The bars Variable To Use Stored Data, 
# Then Make A labels Variable. Create A Series *[]* & Use An fstring Followed By {} *To Indicate Sets (several items in a single variable) & Dictionary literals (1+ key/pair items)*, 
# Add val, To Get The Value Followed By : Then .2f *String Formatting* To Declare That The Value Stops After 2 Decimal Places 
# Create A List Comprehension With df & KPI Column *Run Through Every Value (val) In The KPI Column*,  
# Followed By label_type Location *Chooses Placement Of Data On Bar*, And Fontweight.
# Add Axis Labels, Color & Fontweight
ax.bar_label(bars, labels=[f'{val:.2f}' for val in top_plyr_pass_tch_bx['Passes + Touches In Box']], label_type='center', fontweight='bold')

# Add Axis Labels, Color & Fontweight
plt.title('Players Passes + Touches In Box', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Passes + Touches In Box', fontweight='bold')

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

# Willing To Defend From The Front (Indexing)

### Counterpressures in Opposing Half

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Creates Df Sorting Values The Data Of Column In Descending Order
ctrprs_opp_hlf = cntr_fwds.sort_values(by=['Counterpressures in Opposing Half'], ascending = [False])
ctrprs_opp_hlf

# Find Top 5 Results
top_plyr_ctrprs_opp_hlf = ctrprs_opp_hlf.head(5)

# Replace NaN & inf To 0
top_plyr_ctrprs_opp_hlf.iloc[:, 1:] = top_plyr_ctrprs_opp_hlf.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable And Only Show Selected Columns
top_plyr_ctrprs_opp_hlf[['Name','Team','Primary Position','Counterpressures in Opposing Half']]

## Counterpressure In Opposing Half Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_ctrprs_opp_hlf.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
ctrprs_opp_hlf_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
ctrprs_opp_hlf_percentile_rank['Name'] = top_plyr_ctrprs_opp_hlf['Name']
ctrprs_opp_hlf_percentile_rank['Team'] = top_plyr_ctrprs_opp_hlf['Team']
ctrprs_opp_hlf_percentile_rank['Primary Position'] = top_plyr_ctrprs_opp_hlf['Primary Position']

# Create New Df With Player And Percentile Rank
ctrprs_opp_hlf_percentile_rank = ctrprs_opp_hlf_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins','Aerial Win%','Open Play Final Third Passes','OP Passes Into Box',
                   'Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
ctrprs_opp_hlf_percentile_rank.iloc[:, 3:] = ctrprs_opp_hlf_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
ctrprs_opp_hlf_percentile_rank.iloc[:, 3:] = ctrprs_opp_hlf_percentile_rank.iloc[:, 3:].astype(int)
ctrprs_opp_hlf_percentile_rank[['Name','Team','Primary Position','Counterpressures in Opposing Half']]

### Pressures in Opposing Half

In [ ]:
# Create Variable Using Df And Columns To Use. Add .copy() To Make A New df From Columns In Df So Any Changes Dont Affect Origianl df.
coh_plot = top_plyr_ctrprs_opp_hlf[['Name', 'Team', 'Counterpressures in Opposing Half']].copy()

# Combine Team Name With Players On Xlabel With String Concatination. 
# Create A New Column & Name It. 
# Call df & Name Column. Use + To Combine The Team Column. 
# Use ''. Inside Use (), And Inside That Open Another '' Then Inside Use + Call Df and Team Column Then Close + .
coh_plot['Players Team'] = top_plyr_ctrprs_opp_hlf['Name'] + '\n ('+ top_plyr_ctrprs_opp_hlf['Team'] +')'

# Plot Figure Size.
plt.figure(figsize=(10,6))

# Plot Axes.
ax=plt.axes()

# Set Background Color. (Hex Number)
ax.set_facecolor('#018749')

# Plot Bars.
# Create A Variable To Store The Bars Of The Graph. Plot The bars Inside () With Combine Df, Combined Column (Players_Team) & KPI Column & Change Bar Color.
bars = plt.bar(coh_plot['Players Team'], coh_plot['Counterpressures in Opposing Half'], color='gold')

# Mark Top Player
tp_plyr = 0

# Set Bar Color
bars[tp_plyr].set_color('white')

# Annotate Bars. 
# Create ax.bar_label Function, In () Call The bars Variable To Use Stored Data, 
# Then Make A labels Variable. Create A Series *[]* & Use An fstring Followed By {} *To Indicate Sets (several items in a single variable) & Dictionary literals (1+ key/pair items)*, 
# Add val, To Get The Value Followed By : Then .2f *String Formatting* To Declare That The Value Stops After 2 Decimal Places 
# Create A List Comprehension With df & KPI Column *Run Through Every Value (val) In The KPI Column*,  
# Followed By label_type Location *Chooses Placement Of Data On Bar*, And Fontweight.
# Add Axis Labels, Color & Fontweight
ax.bar_label(bars, labels=[f'{val:.2f}' for val in top_plyr_ctrprs_opp_hlf['Counterpressures in Opposing Half']], label_type='center', fontweight='bold')

# Add Axis Labels, Color & Fontweight
plt.title('Players Counterpressures in Opposing Half', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Counterpressures in Opposing Half', fontweight='bold')

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha="right")

# Displays Figure
plt.show()

In [ ]:
# Create Variable That Creates Df Only Looks At Centre Forwards
cntr_fwds = fwd_data[fwd_data['Primary Position'] == 'Centre Forward']
cntr_fwds

# Create Variable That Creates Df Sorting Values The Data Of Column In Descending Order
prs_opp_hlf = cntr_fwds.sort_values(by=['Pressures in Opposing Half'], ascending = [False])
prs_opp_hlf

# Find Top 5 Results
top_plyr_prs_opp_hlf = prs_opp_hlf.head(5)

# Replace NaN & inf To 0
top_plyr_prs_opp_hlf.iloc[:, 1:] = top_plyr_prs_opp_hlf.iloc[:, 1:].fillna(0).replace([float('inf'), float('-inf')], 0)

# Call Variable And Only Show Selected Columns
top_plyr_prs_opp_hlf[['Name','Team','Primary Position','Pressures in Opposing Half']]

## Pressure In Opposing Half Percentile Ranks

In [ ]:
# Select Numeric Columns Only
numeric_columns=top_plyr_prs_opp_hlf.select_dtypes(include='number')

# Perform Percentile Rank On Each Column
prs_opp_hlf_percentile_rank=numeric_columns.rank(pct=True)*100

# Concatenate Player To New Df
prs_opp_hlf_percentile_rank['Name'] = top_plyr_prs_opp_hlf['Name']
prs_opp_hlf_percentile_rank['Team'] = top_plyr_prs_opp_hlf['Team']
prs_opp_hlf_percentile_rank['Primary Position'] = top_plyr_prs_opp_hlf['Primary Position']

# Create New Df With Player And Percentile Rank
prs_opp_hlf_percentile_rank = prs_opp_hlf_percentile_rank[['Name','Team','Primary Position','Touches In Box','Goals & Penalty Goals','Aerial Wins','Aerial Win%','Open Play Final Third Passes','OP Passes Into Box',
                   'Passes + Touches In Box','Pressures in Opposing Half','Counterpressures in Opposing Half']]

# Replace NaN & Inf With 0 And Handle Non-Numeric Values
# *.apply(pd.to_numeric) Converts Values To Numeric, *errors = 'coerce', Doesnt Bring Up Errors
prs_opp_hlf_percentile_rank.iloc[:, 3:] = prs_opp_hlf_percentile_rank.iloc[:, 3:].apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert Float Columns To Integers
prs_opp_hlf_percentile_rank.iloc[:, 3:] = prs_opp_hlf_percentile_rank.iloc[:, 3:].astype(int)
prs_opp_hlf_percentile_rank[['Name','Team','Primary Position','Pressures in Opposing Half']]

# Plots

In [ ]:
# Plot Figure Size.
plt.figure(figsize=(10,8))

# Create Axes Variable
ax= plt.axes()

# Set Background Color
ax.set_facecolor('#018749')

# Add Team Name Column To X-label Using String Concatination
players_team = top_plyr_prs_opp_hlf['Name'] + '\n ('+ top_plyr_prs_opp_hlf['Team'] + ')'

# Plot Data.
# Call Plot Function. Inside () Call The Previous List *For Data Stored*, df With KPI Columns, Set Marker *o*, Line Type *--* & Color *w*, Marker Size *ms* And Marker Edge Color *mec*
plt.plot(players_team, top_plyr_prs_opp_hlf['Pressures in Opposing Half'],'o--w', ms=7, mec='w')

# Mark Top Player
tp_plyr = 0

# Change Chosen Player Point Stylings
plt.scatter(players_team.iloc[tp_plyr], top_plyr_prs_opp_hlf['Pressures in Opposing Half'].iloc[tp_plyr],
           marker='*', s=300, color='yellow', edgecolor='w', zorder=5)

# Add Axis Labels, Color & Fontweight
plt.title('Player Pressure Into Opponents Half', fontweight='bold')
plt.xlabel('Top 5 Players', fontweight='bold')
plt.ylabel('Presses In Opposition Half', fontweight='bold')

# Show Grid, Plot Only y-axis Lines And Style
plt.grid(axis='y', color='black', linewidth = 1.5)

# Plot xticks Function & Rotate *rotation* (argument) And Move Labels To The Right *ha* (horizontal axis).
plt.xticks(rotation=45, ha='right')

# Displays Figure
plt.show()

# Combined DFS

In [ ]:
# Combine All Dataframes And Concat Them Together To Form One DataFrame
comb_df = [tch_in_bx_percentile_rank, gls_percentile_rank, hder_stats_percentile_rank, hder_perc_stats_percentile_rank, fnl_trd_ps_percentile_rank, 
           opn_ply_pass_box_percentile_rank, pass_tch_bx_percentile_rank, ctrprs_opp_hlf_percentile_rank, prs_opp_hlf_percentile_rank]

# Concatinate All Dfs Together, Drop Any Duplicates And Only Show Top 25 Results
comb_df = pd.concat(comb_df).drop_duplicates().head(25)

# Call DataFrame
comb_df

# Convert Data Frame To Excel

In [ ]:
# Convert Dataframe Into An Excel Spreadsheet
comb_df.to_excel('output.xlsx', sheet_name ='sheet_name_1')